---

- name: get lvm partition info
  become: yes
  parted:
    device: /dev/sda
    state: info
    unit: KiB
  register: sda_info
  tags:
    - disk

- name: create partition
  become: yes
  parted:
    device: /dev/sda
    state: present
    unit: KiB
    number: 3
    flags:
      - lvm
    part_start: "{{ sda_info.partitions[-1].end }}KiB"
  tags:
    - disk

- name: create a volume group
  become: yes
  lvg:
    vg: centos
    pvs: /dev/sda2,/dev/sda3
  tags:
    - disk

- name: resize logical volume
  become: yes
  lvol:
    vg: centos
    lv: home
    resizefs: yes
    size: +100%FREE
  tags:
    - disk

- name: resize filesystem
  become: yes
  filesystem:
    fstype: xfs
    dev: /dev/mapper/centos-home
    resizefs: yes
  tags:
    - disk
