---

- include_tasks: "Amazon-2.yml"
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  tags:
    - disk
    - never
    - experimental

- include_tasks: "CentOS-7.yml"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - disk
    - never
    - experimental

- include_tasks: "Ubuntu-16.yml"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"
  tags:
    - disk
    - never
    - experimental

- include_tasks: "Ubuntu-20.yml"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"
  tags:
    - disk
    - never
    - experimental
