---

- name: install qt
  become: yes
  yum:
    name: qt5-qtbase-devel
    state: present
  tags:
    - qmake

- name: enable qmake
  become: yes
  file:
    src: /usr/bin/qmake-qt5
    dest: /usr/local/bin/qmake
    state: link
  tags:
    - qmake
