---

- name: create temporary directory
  tempfile:
    state: directory
  register: temp
  tags:
    - caddy

- include_tasks: "{{ ansible_architecture }}.yml"
  tags:
    - caddy

- name: copy
  become: yes
  copy:
    src: "{{ temp.path }}/caddy"
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
  tags:
    - caddy

- name: remove temporary directory
  file:
    path: "{{ temp.path }}"
    state: absent
  tags:
    - caddy
