---

- name: "download"
  unarchive:
    src: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.tar.gz"
    dest: "{{ temp.path }}"
    remote_src: yes
  tags:
    - caddy
