---

- name: "install jid"
  become: yes
  unarchive:
    src: https://github.com/simeji/jid/releases/download/v{{ jid_version }}/jid_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  tags:
    - jid
