---

- include_tasks: "{{ ansible_distribution }}.yml"
  tags:
    - python

- name: install pyenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s pyenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - python

- name: install python
  shell: |
    eval "$(anyenv init -)"
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}
    pip install pipenv
  environment:
    CONFIGURE_OPTS: --enable-shared
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - python
