---

- include_tasks: "{{ ansible_distribution }}.yml"
  tags:
    - python

- name: install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_root }}"
  tags:
    - python

- name: install python
  shell: |
    eval "$(pyenv init -)"
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}
    pip install pipenv
  environment:
    CONFIGURE_OPTS: --enable-shared
    PATH: "{{ pyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - python
