---

- include_tasks: "{{ ansible_distribution }}.yml"
  tags:
    - stow

- name: create directory
  become: yes
  file:
    path: /usr/local/stow
    state: directory
    mode: 0755
  tags:
    - stow
