---

- name: create temporary directory
  tempfile:
    state: directory
  register: temp
  tags:
    - fzf

- name: download
  unarchive:
    src: "https://github.com/junegunn/fzf/archive/{{ fzf_version }}.tar.gz"
    dest: "{{ temp.path }}"
    remote_src: yes
  tags:
    - fzf

- name: copy
  become: yes
  copy:
    src: "{{ temp.path }}/fzf"
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
  tags:
    - fzf

- name: remove temporary directory
  file:
    path: "{{ temp.path }}"
    state: absent
  tags:
    - fzf
