---

- name: install packages
  become: yes
  yum:
    state: present
    name:
      - llvm-toolset-7
  tags:
    - llvm

- name: enable packages
  become: yes
  lineinfile:
    path: /etc/profile.d/llvm.sh
    line: . scl_source enable llvm-toolset-7
    create: yes
    mode: 0644
  tags:
    - llvm
