---

- name: install packages
  become: yes
  yum:
    state: present
    name:
      - git236
      - openssh-clients
      - procps-ng
  tags:
    - scm

- name: install git-lfs
  become: yes
  shell: |
    set -o pipefail
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
  args:
    warn: no
  register: result
  changed_when: result.rc == 0
  tags:
    - scm
