---

- name: configure yum
  become: yes
  command: amazon-linux-extras install epel
  register: result
  changed_when: result.rc == 0
  tags:
    - setup

- name: update packages   # noqa package-latest
  become: yes
  yum:
    state: latest
    name: "*"
  tags:
    - setup
