---

- name: configure yum
  become: yes
  yum:
    state: present
    name:
      - yum-utils
      - epel-release
      - centos-release-scl
      - https://centos7.iuscommunity.org/ius-release.rpm
  tags:
    - setup

- name: update packages
  become: yes
  yum:
    state: latest
    name: "*"
  tags:
    - setup
