---

- name: configure yum
  become: yes
  yum:
    state: present
    name:
      - yum-utils
      - epel-release
      - centos-release-scl
      - https://repo.ius.io/ius-release-el7.rpm
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  tags:
    - setup

- name: update packages
  become: yes
  yum:
    state: latest
    name: "*"
  tags:
    - setup
