---

- name: configure apt
  become: yes
  replace:
    dest: /etc/apt/sources.list
    regexp: 'http://(.*\.)?archive\.ubuntu\.com/ubuntu/'
    replace: 'http://jp.archive.ubuntu.com/ubuntu/'
  tags:
    - setup

- name: upgrade packages  # noqa package-latest
  become: yes
  apt:
    state: latest
    update_cache: yes
    name: "*"
  tags:
    - setup

- name: dist-upgrade packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - setup
