---

- name: install packages
  become: yes
  yum:
    state: present
    name:
      - device-mapper-persistent-data
      - lvm2
  tags:
    - docker

- name: add yum repository
  become: yes
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: result
  changed_when: result.rc == 0
  tags:
    - docker

- name: install docker
  become: yes
  yum:
    state: present
    name:
      - docker-ce
  tags:
    - docker

- name: add user to docker group
  become: yes
  command: usermod -aG docker "{{ ansible_user_id }}"
  register: result
  changed_when: result.rc == 0
  tags:
    - docker

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
