---

- name: install docker
  become: yes
  shell: amazon-linux-extras install -y docker
  tags:
    - docker

- name: add user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_user_id }}"
  tags:
    - docker

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
