---

- name: add rpm key
  become: yes
  rpm_key:
    key: https://pkg.osquery.io/rpm/GPG
    state: present
  tags:
    - osquery

- name: add yum repository
  become: yes
  command: yum-config-manager --add-repo https://pkg.osquery.io/rpm/osquery-s3-rpm.repo
  register: result
  changed_when: result.rc == 0
  tags:
    - osquery

- name: install osquery
  become: yes
  yum:
    state: present
    name:
      - osquery
  tags:
    - osquery
